'use strict';

const path = require('path');
const fs   = require('fs');
const { log } = require('../utils/logger');
const { createRL, askChoice, confirm } = require('../utils/prompt');

// Files/folders generated by `init` — safe to remove and regenerate
const GENERATED_TARGETS = [
  { path: '_superml/skills',                    label: 'Skills library',            type: 'dir'  },
  { path: '_superml/module.yaml',               label: 'Skill registry',            type: 'file' },
  { path: '.github/agents',                     label: 'Copilot agent files',       type: 'dir'  },
  { path: '.github/copilot-instructions.md',    label: 'Copilot instructions',      type: 'file' },
  { path: '.github/pull_request_template.md',   label: 'PR template',               type: 'file' },
];

// User-created data — only removed in --all mode with extra confirmation
const USER_DATA_TARGETS = [
  { path: '_superml/config.yml',   label: 'Project config (team settings)',  type: 'file' },
  { path: '_superml/persona.yml',  label: 'Personal config (your settings)', type: 'file' },
  { path: '_superml/reference',    label: 'Reference documents folder',      type: 'dir'  },
  { path: '_superml/meetings',     label: 'Generated meeting docs',          type: 'dir'  },
];

async function run() {
  const projectRoot = process.cwd();
  const rl = createRL();

  try {
    await runClean(rl, projectRoot);
  } finally {
    rl.close();
  }
}

async function runClean(rl, projectRoot) {
  log.banner();
  log.line('  Remove Agentic SDLC generated files from this project.');
  log.line('');

  // Check that there is something to clean
  const hasAny = [...GENERATED_TARGETS, ...USER_DATA_TARGETS]
    .some(t => exists(projectRoot, t));

  if (!hasAny) {
    log.info('Nothing to clean — no Agentic SDLC files found in this directory.');
    return;
  }

  // Choose scope
  const scope = await askChoice(rl, 'What do you want to remove?', [
    {
      label: 'Generated files only  — skills, agents, Copilot instructions, PR template',
      value: 'generated',
    },
    {
      label: 'Everything           — also removes config, persona, reference docs, meetings',
      value: 'all',
    },
  ], 0);

  const targets = scope === 'all'
    ? [...GENERATED_TARGETS, ...USER_DATA_TARGETS]
    : GENERATED_TARGETS;

  // Show what will be removed
  const toRemove = targets.filter(t => exists(projectRoot, t));

  if (toRemove.length === 0) {
    log.info('Nothing found to remove.');
    return;
  }

  log.line('');
  log.line('  Will remove:');
  for (const t of toRemove) {
    log.item(`${t.path}  (${t.label})`);
  }

  if (scope === 'all') {
    log.line('');
    log.warn('This includes your project config and personal settings. They cannot be recovered.');
  }

  log.line('');
  const ok = await confirm(rl, 'Proceed?', false);
  if (!ok) {
    log.line('Clean cancelled.');
    return;
  }

  // Remove
  log.section('Cleaning');
  let removed = 0;
  for (const t of toRemove) {
    const full = path.join(projectRoot, t.path);
    try {
      if (t.type === 'dir') {
        fs.rmSync(full, { recursive: true, force: true });
      } else {
        fs.unlinkSync(full);
      }
      log.success(`Removed  ${t.path}`);
      removed++;
    } catch (err) {
      log.warn(`Could not remove ${t.path}: ${err.message}`);
    }
  }

  // Clean up empty .github dir if nothing left in it
  const githubDir = path.join(projectRoot, '.github');
  if (fs.existsSync(githubDir)) {
    try {
      const remaining = fs.readdirSync(githubDir);
      if (remaining.length === 0) {
        fs.rmdirSync(githubDir);
        log.success('Removed  .github/  (empty)');
      }
    } catch {}
  }

  // Clean up empty _superml dir if everything was removed
  const supermlDir = path.join(projectRoot, '_superml');
  if (fs.existsSync(supermlDir)) {
    try {
      const remaining = fs.readdirSync(supermlDir);
      if (remaining.length === 0) {
        fs.rmdirSync(supermlDir);
        log.success('Removed  _superml/  (empty)');
      }
    } catch {}
  }

  log.line('');
  log.done(`Clean complete — ${removed} item${removed !== 1 ? 's' : ''} removed.`);
  log.line('');

  if (scope === 'generated') {
    log.info('Re-run setup at any time:  npx @supermldev/agentic-sdlc init');
  }
  log.line('');
}

function exists(projectRoot, target) {
  return fs.existsSync(path.join(projectRoot, target.path));
}

module.exports = { run };
